# Training and Testing a Generative Adversarial Network

## Imports and loading in dataset

In [10]:
import tensorflow as tf
from tensorflow.keras import layers, models
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

file_path = "./Datasets/AMZN_2012-06-21_34200000_57600000_orderbook_1.csv"
data = pd.read_csv(file_path)


       2239500  100  2231800  100.1
0      2239500  100  2238100     21
1      2239500  100  2237500    100
2      2239500  100  2237500     74
3      2239500  100  2237500     74
4      2239500  100  2237500     74
...        ...  ...      ...    ...
57509  2206200  100  2205100    300
57510  2206200  100  2205100    249
57511  2206400  100  2205100    249
57512  2206300  100  2205100    249
57513  2206400  100  2205100    249

[57514 rows x 4 columns]


## Preprocessing the data

In [8]:
def preprocess_data(data):
    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaled_data = scaler.fit_transform(data.values)
    return scaled_data

scaled_data = preprocess_data(data=data)
print(scaled_data)
    

[[ 0.24137931 -0.96525706  0.19782214 -0.99882246]
 [ 0.24137931 -0.96525706  0.17604356 -0.99417116]
 [ 0.24137931 -0.96525706  0.17604356 -0.99570196]
 ...
 [-0.9600726  -0.96525706 -1.         -0.98539845]
 [-0.96370236 -0.96525706 -1.         -0.98539845]
 [-0.9600726  -0.96525706 -1.         -0.98539845]]


## Functions to build the training architecture
### Generator

### Discriminator